[package]
name = "fradmin-demissalar"
version = "0.1.0"
compiler = "0.12.0"
entrypoint = "lib.typ"
authors = ["Louis Guichard <glpda+git@pm.me>"]
license = "MIT"
description = "French employee resignation letter template - modèle de lettre de démission du salarié."
repository = "https://github.com/glpda/typst-fradmin"
keywords = ["administration", "letter", "resignation"]
categories = ["office"]
disciplines = ["law"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
